### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by navinbhudiya** [YotpoLtd/magento2-plugin#107]
On product detail page module not working
showing bellow error while click on review start.

**widget.js:1 Uncaught TypeError: Cannot read property 'get' of undefined
    at Function.e.scrollToReviewsTabInMainWidget (widget.js:1)
    at HTMLDivElement.<anonymous> (widget.js:8)**

Magento Version 2.2.5

**Comment by DanGlz** [comment]
Hi @navinbhudiya, thanks for bringing this up.
Which version of magento2-plugin you are using?
Can you provide please more details and screenshots regarding the issue?

Thanks

**Comment by navinbhudiya** [comment]
![image](https://user-images.githubusercontent.com/22772614/47022753-ccaef200-d17b-11e8-9cb2-cebf8d90388f.png)
Magento version 2.2.5
YotpoLtd/magento2-plugin : 2.4

**Comment by DanGlz** [comment]
Hi @navinbhudiya ,
It seems like the Widget is disabled in your Yotpo Configuration page (Admin).
Make sure that the field "Enable Default Widget Position"  is set to ״Yes״.

![screen shot 2018-10-16 at 17 49 05](https://user-images.githubusercontent.com/25307324/47025386-07109300-d16c-11e8-919c-969672c71411.png)

**Comment by navinbhudiya** [comment]
@DanGlz  Thank You so much , it fixed my issue. Thank very much..!

**Comment by jafar247commerce** [comment]
@navinbhudiya , I have made the settings correct, still i am getting the same error.

**Comment by SlavicB** [comment]
@jafar247commerce Can you please link us to the page where you experience the issue
