### ISSUE TITLE
Wrong template path in YotpoReviewRenderer

### ISSUE THREAD

**Issue by tarnum777** [YotpoLtd/magento2-plugin#112]
In file vendor/yotpo/module-review/Block/Product/YotpoReviewRenderer.php there is no such template as         self::SHORT_VIEW => 'Magento_Review::summary_short.phtml',
, it should be 'Magento_Review::helper/summary_short.phtml'

**Comment by DanGlz** [comment]
Hi @tarnum777 ,

Thanks for bringing this up.
This issue (#106) fixed and merged to master. Also, it will be available on the MarketPlace in our next release.
