### ISSUE TITLE
Implement PHP 7.2 support

### ISSUE THREAD

**Issue by chrBrd** [YotpoLtd/magento2-plugin#117]
We're looking to upgrade to PHP 7.2; this module is currently holding us back. Is support for 7.2 planned anytime soon?

**Comment by chrBrd** [comment]
Brilliant @DanGlz, many thanks.

**Comment by DanGlz** [comment]
Hi @chrBrd ,
We released a new version that supports Magento 2.3 and PHP 7.2.
Currently, the installation available via composer and soon will be released on Magento Marketplace.

**Comment by chrBrd** [comment]
Superb @DanGlz, thanks for taking care of it so quickly.
