### ISSUE TITLE
Add support for the rich-snippets API

### ISSUE THREAD

**Issue by mridang** [YotpoLtd/magento2-plugin#39]
We at Nosto are a Yotpo partner and looking to roll out rich-snippet support on M2 as well. The current Yotpo extension doesn't support fetching rich-snippets through the Yotpo API. Here's a reference on how it has been implemented on M1. https://github.com/YotpoLtd/magento-plugin/blob/master/app/code/community/Yotpo/Yotpo/Helper/RichSnippets.php

**Comment by billykov** [comment]
Hi Mridang,
As we support the Rich Snippets out of the box with our JS widgets, we do not require this mechanism.

Therefore, there are no active plans of adding this functionality.

**Comment by Sam-PUMP** [comment]
Hi Billykov

How do we then print out on product pages the number of reviews, the average score as an integer for each product? Thanks

**Comment by billykov** [comment]
Hi @Sam-PUMP 
Sorry I don't follow, can you elaborate?
What exactly do you want to show? The star ratings? or Rich Snippets?

**Comment by Sam-PUMP** [comment]
HI - The Rich Snippets, but or that we need to show the aggregateRating, bestRating, worstRating, ratingValue and reviewCount which are not available on each product page without the rich snippets API (unless there is a way to retrieve all those values on product page by ProductID) ?

Thanks

**Comment by billykov** [comment]
Hi @Sam-PUMP, thanks for elaborating.

There is no way to get those number without calling our API.

**Comment by Sam-PUMP** [comment]
Alright, so then can you re-open issue to add support for the rich snippets api in Magento 2 ? 
Thanks

**Comment by Sam-PUMP** [comment]
Or can you please give link to documentation that shows how to add the required data on the product page in Magento 2 for google to recognize rich snippets (reviews in serp). 
How do we use the JS widget in Magento 2 to get the aggregate rating, average value best and worst etc for each product? Thank you.

**Comment by billykov** [comment]
Sure @Sam-PUMP , you can this endpoint:
http://apidocs.yotpo.com/reference#v1-retrieve-bottom-line-total-reviews-and-average-score-for-all-products

About the other question, I am sorry I dont get it, what do you mean by how do you get the aggregate rating, average value best and worst etc for each product?
