### ISSUE TITLE
Yotpo can't configuration menu

### ISSUE THREAD

**Issue by Samuel-Ayvazyan** [YotpoLtd/magento2-plugin#54]
Yotpo was installed successfully.
I can see Yotpo in Modules enable/disable section: http://prntscr.com/g3ck4y
But I can't see Yotpo configuration menu in Store->Configurations page.
Here is a screenshot for menu: http://prntscr.com/g3clpg

Following commands was successfully:
- composer require yotpo/module-review
- sudo bin/magento setup:upgrade
- sudo bin/magento setup:di:compile

Sorry if it is not right place to ask this question, but was not able to find any forum to discuss this.

**Comment by billykov** [comment]
Hey @Samuel-Ayvazyan,
Yeah, this is not the right place to ask this :)

See if this article helps you - https://support.yotpo.com/en/article/magento-2-installing-yotpo
If not please contact our support via the Yotpo Admin
