### ISSUE TITLE
Uncaught Error: Call to a member function getId() on null

### ISSUE THREAD

**Issue by rain2o** [YotpoLtd/magento2-plugin#62]
When creating a shipment on an order I am seeing this error in our Nginx logs and it throws a 500 in the browser. 
```
PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getId() on null in /vendor/yotpo/module-review/Helper/ApiClient.php:39
```

I tracked the issue down and `$parentId = $item->getProduct()->getId()` was the culprit. It is trying to get the Id before it checks if `getProduct` even returns anything. This was my temporary solution locally. 

In file `Helper/ApiClient.ph` starting at line 39.

Replace:
```
$parentId = $item->getProduct()->getId();
if (!empty($parentId)) {
	$full_product = $this->_productRepository->getById($parentId);
}
```

with 
```
$parent = $item->getProduct();
if ($parent && !empty($parent->getId())) {
	$full_product = $this->_productRepository->getById($parent->getId());
}
```

**Comment by billykov** [comment]
Hey @rain2o 
Thanks!

Why won't you open a pull request and we will add this fix to our next release?

**Comment by rain2o** [comment]
Thanks @billykov . Was in the midst of a site launch yesterday so I wasn't able to go through that process, but I've submitted the pull request now. #63

**Comment by billykov** [comment]
Great stuff - thanks @rain2o
