### ISSUE TITLE
Support PHP7.1 Installs from composer

### ISSUE THREAD

**Issue by friendscottn** [YotpoLtd/magento2-plugin#71]
Is PHP7.1 really not supported, or is this something that can simply be updated in the [composer.json](https://github.com/YotpoLtd/magento2-plugin/blob/master/composer.json) file?

## Steps to Reproduce
- Setup your CLI to run php 7.1
- Run `composer require yotpo/module-review`
## Result
InvalidArgumentException - Could not find package yotpo/module-review at any version matching your PHP version 7.1.11.0

**Comment by billykov** [comment]
@friendscottn We are validating the support for 7.1 and will update about it

**Comment by gabarba** [comment]
Hi what is the status of this as I was  trying to install this on our Magento 2 Dev Server

**Comment by sa3iedsabbah** [comment]
@gabarba Hi, how are you?
what version of Magento2 are you using?

**Comment by gabarba** [comment]
Currently using 2.2.2 CE

**Comment by gabarba** [comment]
Doesn't matter after reviewing the extension I will need to refactor and rewrite portions of it anyways much like I had to do on the Magento 1 version in order to have the features we were looking for.

**Comment by shilpsauce** [comment]
Any updates on this? We are also waiting on this.

**Comment by shilpsauce** [comment]
Looks like there is a pull request for this change. Can we get it merged?

**Comment by indefinitedevil** [comment]
Also need this.

**Comment by object-source** [comment]
Do you have an ETA on this? We cannot use the extension without 7.1.x support

**Comment by Sam-PUMP** [comment]
Can you please merge the pull request for 7.1.x support in composer.json?

**Comment by indefinitedevil** [comment]
This has now been done which I only found out by subscribing to the pull request

**Comment by friendscottn** [comment]
Thanks!
