### ISSUE TITLE
Exception when all 3 blocks are enabled on product page

### ISSUE THREAD

**Issue by miqbal699** [YotpoLtd/magento2-plugin#78]
When I enable all three blocks (i.e. bottomline, yotpo-qa-bottomline, and yotpo-questions) on product details page, Magento throws an exception because of all blocks having the same alias.

Magento version: EE 2.1.6

Exception message: The element 'product.info.main' already has a child with alias 'other' in /vendor/magento/framework/Data/Structure.php:611

Stack trace 1:
#0 /vendor/magento/framework/Data/Structure.php(319): Magento\Framework\Data\Structure->_insertChild('product.info.ma...', 'yotpo-qa-bottom...', NULL, 'other')

Stack trace 2:
#0 /vendor/magento/framework/Data/Structure.php(319): Magento\Framework\Data\Structure->_insertChild('product.info.ma...', 'yotpo-questions', NULL, 'other')

**Comment by bansavage** [comment]
I can confirm this is still an issue in the Yotpo module. Each block mentioned above has an attribute of: `as="other".` Aliases must be unique in a parent container.

**Comment by Sanfam** [comment]
@billykov or anyone else from yotpo, This issue and #80 are effectively duplicates of one another and should be merged.

**Comment by indefinitedevil** [comment]
This is ridiculous. Can this get addressed already? It's been over six months and there's still no fix for this.

**Comment by d6devteam** [comment]
As above, this issue has been outstanding for over 6 months and is causing constant errors on production websites.
