### ISSUE TITLE
Exception - Duplicate 'other' alias in 'product.info.main' 

### ISSUE THREAD

**Issue by xantek-imc** [YotpoLtd/magento2-plugin#80]
![image](https://user-images.githubusercontent.com/6416190/35158237-5ee346f0-fceb-11e7-92d4-adae72c79811.png)

 report.CRITICAL: Magento\Framework\Exception\LocalizedException: The element 'product.info.main' already has a child with alias 'other' in /srv/www/magento2/vendor/magento/framework/Data/Structure.php:611
Stack trace:
#0 /srv/www/magento2/vendor/magento/framework/Data/Structure.php(319): Magento\Framework\Data\Structure->_insertChild('product.info.ma...', 'yotpo-questions', NULL, 'other')
#1 /srv/www/magento2/vendor/magento/framework/View/Layout/ScheduledStructure/Helper.php(196): Magento\Framework\Data\Structure->setAsChild('yotpo-questions', 'product.info.ma...', 'other')
#2 /srv/www/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(115): Magento\Framework\View\Layout\ScheduledStructure\Helper->scheduleElement(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'yotpo-questions')
#3 /srv/www/magento2/vendor/magento/framework/View/Layout/GeneratorPool.php(84): Magento\Framework\View\Layout\GeneratorPool->buildStructure(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure))
#4 /srv/www/magento2/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#5 /srv/www/magento2/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout->generateElements()
#6 /srv/www/magento2/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#7 /srv/www/magento2/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#8 /srv/www/magento2/vendor/magento/framework/View/Page/Config.php(197): Magento\Framework\View\Layout\Builder->build()
#9 /srv/www/magento2/vendor/magento/framework/View/Page/Config.php(207): Magento\Framework\View\Page\Config->build()
#10 /srv/www/magento2/vendor/magento/framework/App/View.php(170): Magento\Framework\View\Page\Config->publicBuild()
#11 /srv/www/magento2/vendor/magento/framework/App/View.php(114): Magento\Framework\App\View->loadLayoutUpdates()
#12 /srv/www/magento2/vendor/magento/module-page-cache/Controller/Block.php(45): Magento\Framework\App\View->loadLayout(Array, true, true, false)
#13 /srv/www/magento2/vendor/magento/module-page-cache/Controller/Block/Render.php(39): Magento\PageCache\Controller\Block->_getBlocks()
#14 /srv/www/magento2/vendor/magento/framework/App/Action/Action.php(102): Magento\PageCache\Controller\Block\Render->execute()
#15 /srv/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#16 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\PageCache\Controller\Block\Render\Interceptor->___callParent('dispatch', Array)
#17 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\PageCac...', 'dispatch', Object(Magento\PageCache\Controller\Block\Render\Interceptor), Array, 'contextPlugin')
#18 /srv/www/magento2/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#19 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\PageCache\Controller\Block\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#20 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\PageCac...', 'dispatch', Object(Magento\PageCache\Controller\Block\Render\Interceptor), Array, 'customer-segmen...')
#21 /srv/www/magento2/vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php(81): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#22 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\CustomerSegment\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\PageCache\Controller\Block\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#23 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\PageCac...', 'dispatch', Object(Magento\PageCache\Controller\Block\Render\Interceptor), Array, 'customer-app-ac...')
#24 /srv/www/magento2/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#25 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\PageCache\Controller\Block\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#26 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\PageCac...', 'dispatch', Object(Magento\PageCache\Controller\Block\Render\Interceptor), Array, 'storeCheck')
#27 /srv/www/magento2/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\PageCache\Controller\Block\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\PageCac...', 'dispatch', Object(Magento\PageCache\Controller\Block\Render\Interceptor), Array, 'weee-app-action...')
#30 /srv/www/magento2/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#31 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\PageCache\Controller\Block\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#32 /srv/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\PageCac...', 'dispatch', Object(Magento\PageCache\Controller\Block\Render\Interceptor), Array, 'tax-app-action-...')
#33 /srv/www/magento2/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(91): Magento\PageCache\Controller\Block\Render\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#34 /srv/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\PageCache\Controller\Block\Render\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /srv/www/magento2/var/generation/Magento/PageCache/Controller/Block/Render/Interceptor.php(26): Magento\PageCache\Controller\Block\Render\Interceptor->___callPlugins('dispatch', Array, Array)
#36 /srv/www/magento2/vendor/magento/framework/App/FrontController.php(55): Magento\PageCache\Controller\Block\Render\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#37 /srv/www/magento2/vendor/magento/framework/Interception/Interceptor.php(74): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#38 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#39 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#40 /srv/www/magento2/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#41 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#42 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#43 /srv/www/magento2/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#44 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#45 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#46 /srv/www/magento2/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain\{closure}(Object(Magento\Framework\App\Request\Http))
#47 /srv/www/magento2/vendor/magento/framework/Interception/Chain/Chain.php(67): Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#48 /srv/www/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#49 /srv/www/magento2/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(69): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#50 /srv/www/magento2/vendor/magento/framework/Interception/Interceptor.php(142): Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /srv/www/magento2/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#52 /srv/www/magento2/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#53 /srv/www/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#54 /srv/www/magento2/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#55 {main} [] []

**Comment by bansavage** [comment]
I can confirm this is still an issue in the Yotpo module. Each block mentioned above has an attribute of: `as="other"`. Aliases must be unique in a parent container.

**Comment by vrajeshpatel4u** [comment]
I have installed Yotpo in Magento 2.2.5 and still this issue in exception.

**Comment by SlavicB** [comment]
@vrajeshkpatel Should be good now, can you please let us know if you're still experiencing issues.
