### ISSUE TITLE
main.CRITICAL: Invalid template file: 'yotpo-questions.phtml' in module: 'Yotpo_Yotpo' block's name: 'yotpo-questions' []

### ISSUE THREAD

**Issue by py4762013** [YotpoLtd/magento2-plugin#82]
main.CRITICAL: Invalid template file: 'yotpo-questions.phtml' in module: 'Yotpo_Yotpo' block's name: 'yotpo-questions' [] []

**Comment by asnecommerce** [comment]
Getting this error too, plus others:
[2018-08-06 04:41:12] report.CRITICAL: Invalid template file: 'helper/yotposummary.phtml' in module: 'Yotpo_Yotpo' block's name: '' [] []
[2018-08-06 04:41:14] report.CRITICAL: Invalid template file: 'yotpo-questions.phtml' in module: 'Yotpo_Yotpo' block's name: 'yotpo-questions' [] []

**Comment by allanpaiste** [comment]
I place my bets on someone forgetting to add certain new files to the latest release. 

@aberenshtein, maybe you can comment on that?

**Comment by asnecommerce** [comment]
Would be awesome to get a fix for this seeing as the issue was first raised at the start of February.

**Comment by asnecommerce** [comment]
@DanGlz Were these issues fixed?

**Comment by DanGlz** [comment]
check the last release - 2.4

‫בתאריך יום ד׳, 22 באוג׳ 2018 ב-1:12 מאת ‪asnecommerce‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by allanpaiste** [comment]
Just looking at the code of the block class - I'd say it's fixed :)
