### ISSUE TITLE
Warning: Ambiguous class resolution while doing `composer dump-autoload -o`

### ISSUE THREAD

**Issue by enl** [YotpoLtd/magento2-plugin#83]
```
Warning: Ambiguous class resolution, 
"Yotpo\\Yotpo\\Block\\Product\\YotpoReviewRenderer" 
was found in both 
"/private/var/www/hellyhansen22/vendor/yotpo/module-review/Product/YotpoReviewRenderer.php" 
and "/private/var/www/hellyhansen22/vendor/yotpo/module-review/Block/Product/YotpoReviewRenderer.php", 
the first will be used.
```

**Step to reproduce:**
1. `composer require yotpo/module-review`
2. `composer dump-autoload -o`

This actually means that there are two classes with exactly the same name in the module, but located in different folders.

**Comment by peterjaap** [comment]
Yep, same error here when running `composer install -vvv`;

`Warning: Ambiguous class resolution, "Yotpo\Yotpo\Block\Product\YotpoReviewRenderer" was found in both "/builds/steunkousen/magento2/vendor/yotpo/module-review/Block/Product/YotpoReviewRenderer.php" and "/builds/steunkousen/magento2/vendor/yotpo/module-review/Product/YotpoReviewRenderer.php", the first will be used.`

**Comment by Jakhotiya** [comment]
That's happening because there is duplicate class in Product directory. So there are two classes with same namespace , one in Block/Product directory and one in Product directory. I will fix it and send a pull request in some time.

**Comment by pengleelove** [comment]
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.  it's Ok
